---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(readxl)
library(tidyverse)
library(lmtest)
library(car)
library(lsmeans)
library(tidyverse)
library(glmmTMB)
```

```{r}
# Read in Data
tib <- read_excel("/Users/angelicefloyd/Documents/Documents/ST542_Statistical_Practice/RADPAD_Study/ST-542-RADPAD-Project/RADPAD DATA Stats team 5_28_24_FINAL.xlsx", skip = 1)
```

```{r}
# Select and Rename Relevant Columns

tib <- tib %>% 
  mutate(Index = seq(1, nrow(tib), by = 1)) %>%
  select(Index, `Weight (kg)`, `Procedure  type (BPV, PDA PMI, PV Stent)`, `RADPAD Drape Used? Y/N`, 
         `Faculty`, `Tech 1`, `Resident 1`, `Resident 2`, `TEE`, `Anesthesia`, `Patient...2`, `Total fluoro time (min)`, `DAP Total (Gycm2)`) %>% 
  rename("Weight" = `Weight (kg)`, "Procedure_Type" = `Procedure  type (BPV, PDA PMI, PV Stent)`, 
         "RADPAD" = `RADPAD Drape Used? Y/N`, "Tech1" = `Tech 1`, "Resident1" = `Resident 1`, 
         "Resident2" = `Resident 2`, "Patient" = `Patient...2`,"Time" = `Total fluoro time (min)`, "DAP" = `DAP Total (Gycm2)`)

#Convert to Character Type and Pivot Long Format
tib[,c("Index", "Procedure_Type", "RADPAD", "Faculty", "Tech1", "Resident1", "Resident2", "TEE", "Patient")]  <- 
  lapply(tib[,c("Index", "Procedure_Type", "RADPAD", "Faculty", "Tech1", "Resident1", "Resident2", "TEE", "Patient")] , as.character)

tib <- tib %>%
  pivot_longer(cols = Faculty:Patient, names_to = "Lab_Personnel", values_to = "Dose")

tib_ <- tib %>% 
  filter((Dose != "n/a") & (Dose != "NB") & (Dose != "n /a") & (Lab_Personnel != "Patient")) %>%
  mutate(Dose = as.numeric(Dose), Relative_Dose = as.numeric(Dose)/DAP) 

tib_$Procedure_Type[tib_$Procedure_Type == "PV stent"] <- "PV Stent"
```


```{r}
hist_0 <- ggplot(tib_)+ 
  geom_histogram(mapping=aes(x=Dose), position="identity", bins = 50) + 
  labs(x ="dosage Level", title =  "Counts for dosage Level by Procedure Type") + 
  facet_wrap(.~Lab_Personnel)


hist_0
```


```{r}
#Box Cox transformation 
library(MASS)
m <- lm((Dose + 1) ~ RADPAD*Procedure_Type*Lab_Personnel,
        data = tib_)
b <- boxcox(m, plotit = FALSE)

b$x[which.max(b$y)]

tran <- make.tran("power", param = c(-0.5, -1))

tib_$box <- with(tran,linkfun(tib_$Dose))

```

```{r}

#Box Cox Hist 

hist_1 <- ggplot(tib_)+ 
  geom_histogram(mapping=aes(x=box), position="identity", bins = 50) + 
  labs(x ="dosage Level", title =  "Counts for dosage Level by Procedure Type") + 
  facet_wrap(.~Lab_Personnel)


hist_1
```




#Gamma Regression
```{r}
#fit a GLM with gamma family
tib_r1 <- tib_ %>% filter(Lab_Personnel == 'Resident1')
#unequal variance between RADPAD levels
gls.fit2 <- gls(box ~ RADPAD * Procedure_Type + Weight + Time, 
    data = tib_r1,
    weights = varIdent(form = ~ 1 | RADPAD))


#get the residuals (standardized)
residual <- residuals(gls.fit2, type = 'pearson')
#get the fitted values
fitted_values <- fitted(gls.fit2)
#plot residuals vs fitted
plot(fitted_values, residual, xlab = "Fitted values", ylab = "Pearson residuals", main = "Residuals vs Fitted", pch = 1, col = "dodgerblue")
abline(h=0)
#normal QQ plot
qqnorm(residual, pch = 1, col = "dodgerblue")
abline(0,1, lwd=2)


white_test <- data.frame(
  residuals = residual,
  fitted_values = fitted_values)
#conduct White Test
bptest(I(residuals^2) ~ fitted_values + I(fitted_values^2), data = white_test)
```

```{r}
#fit a GLM with gamma family for TEE
tib_r1 <- tib_ %>% filter(Lab_Personnel == 'TEE')
#unequal variance between RADPAD levels
gls.fit2 <- gls(box ~ RADPAD * Procedure_Type + Weight + Time, 
    data = tib_r1,
    weights = varIdent(form = ~ 1 | RADPAD))


#get the residuals (standardized)
residual <- residuals(gls.fit2, type = 'pearson')
#get the fitted values
fitted_values <- fitted(gls.fit2)
#plot residuals vs fitted
plot(fitted_values, residual, xlab = "Fitted values", ylab = "Pearson residuals", main = "Residuals vs Fitted", pch = 1, col = "dodgerblue")
abline(h=0)
#normal QQ plot
qqnorm(residual, pch = 1, col = "dodgerblue")
abline(0,1, lwd=2)


white_test <- data.frame(
  residuals = residual,
  fitted_values = fitted_values)
#conduct White Test
bptest(I(residuals^2) ~ fitted_values + I(fitted_values^2), data = white_test)
```

```{r, fig.show = "hold", out.width = "100%", out.height = "46%"}
#fit zero-inflated gamma model
zig.fit2 <- glmmTMB(Relative_Dose ~ RADPAD*Procedure_Type + Weight + Time,
                  ziformula = ~ 1,
                  family = ziGamma(link = "log"), 
                  data = tib_ %>% filter(Lab_Personnel == "Faculty"))
#fit zero-inflated gamma model
zig.fit3 <- glmmTMB(Relative_Dose ~ RADPAD*Procedure_Type + Weight + Time,
                  ziformula = ~ 1+RADPAD,
                  family = ziGamma(link = "log"), 
                  data = tib_ %>% filter(Lab_Personnel == "Resident2"))
#fit zero-inflated gamma model
zig.fit4 <- glmmTMB(Relative_Dose ~ RADPAD*Procedure_Type + Weight + Time,
                  ziformula = ~ 1+RADPAD,
                  family = ziGamma(link = "log"), 
                  data = tib_ %>% filter(Lab_Personnel == "Anesthesia"))
#diagnostic plots
plot(DHARMa:: simulateResiduals(fittedModel = zig.fit2))
plot(DHARMa:: simulateResiduals(fittedModel = zig.fit3))
plot(DHARMa:: simulateResiduals(fittedModel = zig.fit4))

```







