---
title: "Mann-Whitney U Tests"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(emmeans)
library(broom)
```

Advantages:

- Does not make any assumptions about the distribution of the data.
- Less affected by outliers compared to parametric tests.

Disadvantages:

- Not controlling for weight/time.
- Less powerful than parametric tests (given assumptions can be met).

```{r}
r <- read_csv("radpad.csv") |>
  mutate(Relative_Dose = Dose/Patient_DAP)

rY <- r |>
  filter(RADPAD == "Y")
rN <- r |>
  filter(RADPAD == "N")
```

## Resident 1

```{r}
wilcox.test(filter(rY, Occupation == "Resident 1")$Relative_Dose,
            filter(rN, Occupation == "Resident 1")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```

\newpage

## Resident 2

```{r}
wilcox.test(filter(rY, Occupation == "Resident 2")$Relative_Dose,
            filter(rN, Occupation == "Resident 2")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```

\newpage

## Faculty

```{r}
wilcox.test(filter(rY, Occupation == "Faculty")$Relative_Dose,
            filter(rN, Occupation == "Faculty")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```

\newpage

## Anesthesia

```{r}
wilcox.test(filter(rY, Occupation == "Anesthesia")$Relative_Dose,
            filter(rN, Occupation == "Anesthesia")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```
\newpage

## TEE

```{r}
wilcox.test(filter(rY, Occupation == "TEE")$Relative_Dose,
            filter(rN, Occupation == "TEE")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```

\newpage

## Tech 1

```{r}
wilcox.test(filter(rY, Occupation == "Tech 1")$Relative_Dose,
            filter(rN, Occupation == "Tech 1")$Relative_Dose,
            paired = FALSE,
            conf.int = TRUE)
```